Uwp attachments
Esri/data-collection-dotnet pull request #33
Opened 2019-05-22 00:50 UTC by codergrl

@nCastle1 please review
- wired up deleting attachments
- wired up adding new attachments from file and from camera

2019-05-22 01:50 UTC, nCastle1 requested changes
Looks good!

One thing, I noticed a crash when attempting to open a recently uploaded (within the session) attachment - filename is null and that causes an exception when creating the FileInfo in *AttachmentsViewModel.cs:161*. 

Only other change I would suggest is clarifying the language used in the attachment deletion warning. It looks like the changes are only persisted after the user explicitly saves, but the warning suggests that as soon as the user hits delete, the attachment is permanently gone.

2019-05-22 01:50 UTC, nCastle1 commented on src/DataCollection.UWP/Views/IdentifiedFeaturePopup.xaml.cs
> +            _identifiedFeatureViewModel.AttachmentsViewModel.NewAttachmentFile = await MediaHelper.RecordMediaAsync();
I would check for exceptions here. If the user uses 'Esc' to close the file name dialog, the file gets saved as `.jpg`; doing that more than once throws an exception due to the duplicate name.

2019-05-22 01:50 UTC, nCastle1 commented on src/DataCollection.UWP/Views/IdentifiedFeaturePopup.xaml.cs
> +            _identifiedFeatureViewModel.AttachmentsViewModel.NewAttachmentFile = await MediaHelper.RecordMediaAsync();
Or just doing multiple attachments without changing the name will also throw an exception

2019-05-22 01:50 UTC, nCastle1 commented on src/DataCollection.UWP/Views/OriginRelatedRecordPopup.xaml.cs
> +        private async void CaptureMediaButton_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
Could these be refactored to be commands instead of using click event handlers?

2019-05-24 18:21 UTC, mikewilburn commented
@nCastle1 
> Only other change I would suggest is clarifying the language used in the attachment deletion warning. It looks like the changes are only persisted after the user explicitly saves, but the warning suggests that as soon as the user hits delete, the attachment is permanently gone.

I think the plan was to update this message with something to the effect of "deleted attachments will be permanently gone once the edits are saved" but without using jargon that requires the user be aware of the fact that they're in an active 'edit' session. One possibility to ease this was by referencing the tooltip text of the button with the save icon, but that would also require adding that tooltip text first. Sounds like that didn't make it in here.

2019-05-29 18:27 UTC, nCastle1 commented on src/DataCollection.UWP/Views/OriginRelatedRecordPopup.xaml.cs
> +        private async void CaptureMediaButton_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
Looking at this closer, I see why maybe it isn't as straightforward to do this - the behavior and expectations vary significantly between platforms, enough that is probably doesn't make sense to move that to shared code.

2019-06-05 18:38 UTC, dotMorten requested changes
Generally looking good, but see comments

2019-06-05 18:38 UTC, dotMorten commented on src/DataCollection.Shared/ViewModels/AttachmentsViewModel.cs
> +            }
Don't read files into byte-arrays. Large files could cause out-of-memory.

2019-06-05 18:38 UTC, dotMorten commented on src/DataCollection.Shared/ViewModels/AttachmentsViewModel.cs
> +        // HACK: works around issues with attachment management in the UWP sandbox. See OpenAttachment above for details.
It's not a hack nor a workaround. It's dealing with the sandbox.

2019-06-05 18:38 UTC, dotMorten commented on src/DataCollection.UWP/DataCollection.UWP.csproj
> +    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.17763.0</TargetPlatformVersion>
Why this? If you rely on 17763, make sure those APIs you need for that are guarded against if running on 16299

2019-06-05 18:38 UTC, dotMorten commented on src/DataCollection.UWP/DataCollection.UWP.csproj
> +    <AppxBundlePlatforms>x86|x64|arm</AppxBundlePlatforms>
arm64 missing

2019-06-05 18:38 UTC, dotMorten commented on src/DataCollection.UWP/Helpers/MediaHelper.cs
> +        /// Calls camera API to capute photo pr video
nit: typo :)

2019-06-05 18:38 UTC, dotMorten commented on src/DataCollection.UWP/Views/OriginRelatedRecordPopup.xaml.cs
> +            _identifiedFeatureViewModel.SelectedOriginRelationship.AttachmentsViewModel.NewAttachmentFile = await MediaHelper.RecordMediaAsync();
`async void` methods should have try/catch on any awaited methods.

2019-06-06 20:30 UTC, mikewilburn commented
One behavior I'm noticing so far is that when canceling the download of an offline map, it seems to always kill the app. Commenting here in case that might have been introduced by this PR.

2019-06-10 22:52 UTC, merged