Add TOC and bookmarks to data collection
Esri/data-collection-dotnet pull request #92
Opened 2020-02-19 03:01 UTC by nCastle1

Notes:

* Major UWP UI changes (driven by changes needed by WinUI to get treeview)
* Adds toolkit preview package on WPF

2020-02-19 18:53 UTC, ZackAllen requested changes
The add button on UWP does not work on my machine.

2020-02-19 18:53 UTC, ZackAllen commented on src/DataCollection.WPF/MainWindow.xaml
> +        <Grid Grid.Row="1"
I feel like the TOC would really benefit from some type of border. It feels unfinished with the white background with no rounded corners.

2020-02-19 18:53 UTC, ZackAllen commented on src/DataCollection.WPF/MainWindow.xaml
> +            <esri:TableOfContents GeoView="{Binding ElementName=MapView, Mode=OneWay}" ShowLegend="False" />
If possible, changing the font family here could look better.

2020-02-19 18:53 UTC, ZackAllen commented on src/DataCollection.WPF/MainWindow.xaml
> +              Margin="0,5,5,0"
I think this needs a larger vertical margin.

2020-02-19 18:53 UTC, ZackAllen commented on src/DataCollection.UWP/MainPage.xaml
> +                x:Uid="ShowBookmarksButton"
After downloading a map, having a bookmark to return to the view of the offline section would be useful. When downloading a small section, then navigating away with a bookmark, it is hard to find the offline section where a map is visible.

2020-02-19 18:56 UTC, ZackAllen commented
![DataCollection WPF_cZ0N2Qw3SI](https://user-images.githubusercontent.com/16495151/74865691-635a6880-5306-11ea-8de8-fb45ecfa5abd.jpg)

ToC does not align to the side when using the WPF app in full screen.

2020-02-19 22:26 UTC, ZackAllen approved these changes
Drop shadow helped WPF a lot.

2020-02-20 21:50 UTC, esreli commented
A tip, take it or leave it. You might consider adding lines to the README as you go, that way the RELEASE notes aggregate as you add to the project rather than having to go back at the end and remember what work was completed.

2020-02-26 17:25 UTC, nCastle1 commented
@ZackAllen Can you please re-review? I made some UI changes and I'd like to verify they're good before retaking screenshots.

2020-02-27 22:00 UTC, ZackAllen approved these changes
Both UIs look great

2020-02-28 04:34 UTC, merged